### PR TITLE
Multi clause printf

### PR DESCRIPTION
**Pull request by dosumis**
#71

### CODE REVIEW

**Review by dosumis — COMMENTED** [review]
Looks good to me.  Would be good to see test cases in PR.  Is testing with updated architecture wired up to GitHub Actions?

**Comment by hkir-dev** [comment]
> Looks good to me. Would be good to see test cases in PR. Is testing with updated architecture wired up to GitHub Actions?

Updated architecture and test classes exist in another branch and we need to merge it first. https://github.com/INCATools/dead_simple_owl_design_patterns/pull/74

Afterwards there will be a conflict in this branch and I can resolve and add related tests.

Current github action is only for release, I can add a new one for running tests.

**Comment by dosumis** [comment]
> Updated architecture and test classes exist in another branch and we need to merge it first: #74. We don't have test cases in this branch.

> Afterwards there will be a conflict in this branch and I can resolve and add related tests.

Branch with tests + architecture for running them should be merged down to master first.  Then merged to this branch.  

> Current github action is only for release, I can add a new one for running tests.

Some basic tests used to run on Travis_ci - but guess these now dropped.  Branch should not be merged until tests running on it.  Simplest test = is this valid JSON schema? (validator does this already when loading schema)

**Review by dosumis — COMMENTED** [review]
Approved.  (Can't approve officially as I initiated the PR)

**Pull request merged**
