### PR TITLE
Single quote test ms only

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by dosumis** [comment]
Fixed using JPATH to enumerate MS text fields.  (other changes are just tidying and updating travis tests).

**Review by balhoff — COMMENTED** [review]
Thanks! Would it be hard to also add `logical_axioms` (`text` inside each list item).

**Comment by dosumis** [comment]
Nit sure I follow.  This covers the possible types of path for MS text fields:

`logical_axioms.[*].text` e.g. - [example](https://github.com/INCATools/dead_simple_owl_design_patterns/blob/single_quote_test_MS_only/spec/test/test_positive.yaml#L48)
`equivalentTo|subClassOf|GCI|disjointWith.text` - [example](https://github.com/INCATools/dead_simple_owl_design_patterns/blob/75b32ed7e7e291e55f5fc8bea98d89ede6ebfab2/spec/test/cellPartOfAnatomicalEntity.yaml#L35)

Am i missing something (besides that I should really have suite of tests - including tests for failure.)

**Comment by balhoff** [comment]
Sorry, my mistake! I missed that line somehow. Looks good!

**Review by balhoff — APPROVED** [review]

**Pull request merged**
